/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import clases.Marca;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.MarcaDAO;

/**
 *
 * @author PC
 */
public class panelMarcas_2 extends javax.swing.JPanel {

    private Marca c;
    private MarcaDAO cd = new MarcaDAO();
    private DefaultTableModel modelo;

    public panelMarcas_2() {
        initComponents();
        cargarTabla();
        this.lbl_ID.setVisible(false);
    }

    private void limpiar() {
        this.txtNombre.setText("");
        this.lbl_ID.setText("");
        this.comboCalidad.setSelectedIndex(0);
        cargarTabla();
    }

    private void cargarTabla() {

        String titulos[] = {"ID", "NOMBRE", "CALIDAD"};
        modelo = new DefaultTableModel(titulos, 0);
        List<Marca> lp = cd.listarMarca();
        for (Marca p : lp) {
            modelo.addRow(new Object[]{p.getId(), p.getNombre(), p.getCalidad()});
        }
        this.tablaProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        comboCalidad = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 218, 157));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 430, 260));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MARCAS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("NOMBRE:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        txtNombre.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 200, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 120, 30));

        btnModificar.setBackground(new java.awt.Color(255, 102, 0));
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 110, 30));

        btnAgregar.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 120, 30));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CALIDAD:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lbl_ID.setForeground(new java.awt.Color(255, 218, 157));
        add(lbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 40, 30));

        comboCalidad.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        comboCalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Mala", "Regular", "Buena", "Muy Buena", "Excelente" }));
        add(comboCalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!this.lbl_ID.equals("")) {

            if (cd.eliminarMarca(Integer.valueOf(this.lbl_ID.getText()))) {
                limpiar();
                JOptionPane.showMessageDialog(this, "Se Elimino correctamente");
            } else {
                limpiar();
                JOptionPane.showMessageDialog(this, "No se Elimino");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una Marca");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        if (this.comboCalidad.getSelectedIndex() != 0) {
            String nombre = this.txtNombre.getText();
            String ubicacion = this.comboCalidad.getSelectedItem().toString();
            c = new Marca(nombre, ubicacion);
            if (cd.registrarMarca(c)) {
                limpiar();
                JOptionPane.showMessageDialog(this, "Se Registro correctamente");
            } else {
                limpiar();
                JOptionPane.showMessageDialog(this, "No se registro");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione la calidad");
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!this.lbl_ID.equals("")) {

            if (this.comboCalidad.getSelectedIndex() != 0) {
                String nombre = this.txtNombre.getText();
                String ubicacion = this.comboCalidad.getSelectedItem().toString();
                int id = Integer.valueOf(this.lbl_ID.getText());
                c = new Marca(id, nombre, ubicacion);
                if (cd.modificarMarca(c)) {
                    limpiar();
                    JOptionPane.showMessageDialog(this, "Se Modifico correctamente");
                } else {
                    limpiar();
                    JOptionPane.showMessageDialog(this, "No se Modifico");
                }
            } else {

                JOptionPane.showMessageDialog(this, "Seleccione la calidad");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una Marca");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked

        int fila = this.tablaProductos.rowAtPoint(evt.getPoint());
        this.lbl_ID.setText(this.tablaProductos.getValueAt(fila, 0).toString());
        this.txtNombre.setText(this.tablaProductos.getValueAt(fila, 1).toString());
        this.comboCalidad.getModel().setSelectedItem(this.tablaProductos.getValueAt(fila, 2).toString());
    }//GEN-LAST:event_tablaProductosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> comboCalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
