/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import clases.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.VendedorDAO;

/**
 *
 * @author PC
 */
public class panelVendedores extends javax.swing.JPanel {

    private Usuario v;
    private final VendedorDAO vd = new VendedorDAO();
    private DefaultTableModel modelo;

    public panelVendedores() {
        initComponents();
        cargarTabla();
    }

    private void limpiar() {
        this.txtCedula.setText("");
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtSueldo.setText("");
        this.txtCelular.setText("");
        this.txtContra.setText("");
        this.txtContra2.setText("");

        cargarTabla();
    }

    private void cargarTabla() {
        String titulos[] = {"CEDULA", "NOMBRE", "APELLIDO", "SUELDO", "CELULAR", "CONTRASEÑA"};
        modelo = new DefaultTableModel(titulos, 0);
        List<Usuario> lp = vd.listarVendedor();
        for (Usuario p : lp) {
            modelo.addRow(new Object[]{p.getCedula(), p.getNombre(), p.getApellido(), p.getSueldo(), p.getCelular(), p.getContra()});
        }
        this.tablaVendedores.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgergar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtSueldo = new javax.swing.JFormattedTextField();
        txtContra = new javax.swing.JPasswordField();
        txtContra2 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 218, 157));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVendedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVendedores);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 510, 260));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTION DE VENDEDORES");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CEDULA :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        txtCedula.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 170, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NOMBRE :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 170, -1));

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("APELLIDO :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtApellido.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 170, -1));

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("CELULAR :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        txtCelular.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 170, -1));

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SUELDO :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CONTRASEÑA :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("CONTRASEÑA :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        btnEliminar.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 120, 30));

        btnModificar.setBackground(new java.awt.Color(255, 102, 0));
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 110, 30));

        btnAgergar.setBackground(new java.awt.Color(255, 102, 0));
        btnAgergar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgergar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgergar.setText("AGREGAR");
        btnAgergar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnAgergar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgergarActionPerformed(evt);
            }
        });
        add(btnAgergar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, 30));

        txtSueldo.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 170, -1));

        txtContra.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 170, 20));

        txtContra2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        add(txtContra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 170, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (!this.txtCedula.equals("")) {

            if (vd.eliminarVendedor(this.txtCedula.getText())) {
                limpiar();
                JOptionPane.showMessageDialog(this, "Se Elimino correctamente");
            } else {
                limpiar();
                JOptionPane.showMessageDialog(this, "No se Elimino el Vendedor");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un Ruc");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgergarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgergarActionPerformed
        String cedula = this.txtCedula.getText();
        String nombre = this.txtNombre.getText();
        String apellido = this.txtApellido.getText();
        String celular = this.txtCelular.getText();
        Double sueldo = Double.valueOf(this.txtSueldo.getText());
        String contra = new String(this.txtContra.getPassword());
        String confContra = new String(this.txtContra2.getPassword());

        if (contra.equals(confContra)) {
            v = new Usuario(cedula, confContra, nombre, apellido, sueldo, celular);
            if (vd.registrarVendedor(v)) {
                limpiar();
                JOptionPane.showMessageDialog(this, "Se Registro correctamente");
            } else {
                limpiar();
                JOptionPane.showMessageDialog(this, "No se registro el Vendedor");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Las Contraseñas No coinciden");
        }


    }//GEN-LAST:event_btnAgergarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (!this.txtCedula.equals("")) {

            String cedula = this.txtCedula.getText();
            String nombre = this.txtNombre.getText();
            String apellido = this.txtApellido.getText();
            String celular = this.txtCelular.getText();
            Double sueldo = Double.valueOf(this.txtSueldo.getText());
            String contra = new String(this.txtContra.getPassword());
            String confContra = new String(this.txtContra2.getPassword());

            if (contra.equals(confContra)) {
                v = new Usuario(cedula, confContra, nombre, apellido, sueldo, celular);
                if (vd.modificarVendedor(v)) {
                    limpiar();
                    JOptionPane.showMessageDialog(this, "Se MOdifico correctamente");
                } else {
                    limpiar();
                    JOptionPane.showMessageDialog(this, "No se modifico el Vendedor");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Las Contraseñas No coinciden");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese una Cedula");
        }

    }//GEN-LAST:event_btnModificarActionPerformed

    private void tablaVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVendedoresMouseClicked
        int fila = this.tablaVendedores.rowAtPoint(evt.getPoint());
        this.txtCedula.setText(this.tablaVendedores.getValueAt(fila, 0).toString());
        this.txtNombre.setText(this.tablaVendedores.getValueAt(fila, 1).toString());
        this.txtApellido.setText(this.tablaVendedores.getValueAt(fila, 2).toString());
        this.txtSueldo.setText(this.tablaVendedores.getValueAt(fila, 3).toString());
        this.txtCelular.setText(this.tablaVendedores.getValueAt(fila, 4).toString());
        this.txtContra.setText(this.tablaVendedores.getValueAt(fila, 5).toString());
    }//GEN-LAST:event_tablaVendedoresMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgergar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaVendedores;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JPasswordField txtContra;
    private javax.swing.JPasswordField txtContra2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
