package vista;

import clases.Genericos;
import clases.Marca;
import clases.Producto_;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import modelo.GenericosDAO;
import modelo.MarcaDAO;
import modelo.productoDAO_;

public class panelBuscar extends javax.swing.JPanel {

    private Producto_ p = new Producto_();
    private productoDAO_ pd = new productoDAO_();
    private MarcaDAO md = new MarcaDAO();
    private GenericosDAO gd = new GenericosDAO();
    private DefaultTableModel modelo;

    public panelBuscar() {
        initComponents();
        this.lbl_ID.setVisible(false);
        cargarGenericos();
        cargarMarcas();
    }

    private void limpiar() {
        this.lbl_ID.setText("");
        this.comboMarca.setSelectedIndex(0);
        this.comboTipo.setSelectedIndex(0);
        limpiarTabla(modelo);
    }

    public void cargarMarcas() {
        List<Marca> lt = md.listarMarca();
        this.comboMarca.removeAllItems();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        comboMarca.setModel(dc);
        dc.addElement("Seleccione");
        for (Marca t : lt) {
            dc.addElement(new Marca(t.getId(), t.getNombre()));
        }
    }

    public void cargarGenericos() {
        List<Genericos> lt = gd.listarGenericos();
        this.comboTipo.removeAllItems();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        comboTipo.setModel(dc);
        dc.addElement("Seleccione");
        for (Genericos t : lt) {
            dc.addElement(new Genericos(t.getId(), t.getNombre()));
        }
    }

    public void limpiarTabla(DefaultTableModel model) {
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setRowCount(0);
        }
    }

    private void cargarTabla() {
        String sql = "SELECT * FROM productos WHERE 1=1";
        if (!comboTipo.getSelectedItem().equals("Seleccione")) {
            sql += " AND ID_PRO_GEN = "+((Genericos) this.comboTipo.getSelectedItem()).getId();
        }
        if (!comboMarca.getSelectedItem().equals("Seleccione")) {
            sql += " AND ID_MAR_PRO = "+((Marca) this.comboMarca.getSelectedItem()).getId();
        }
         sql += ";";
        modelo = (DefaultTableModel) tablaProductos.getModel();
        modelo.setRowCount(0);
        gd.listarQuery(modelo, sql);
        this.tablaProductos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        comboMarca = new javax.swing.JComboBox<>();
        comboTipo = new javax.swing.JComboBox<>();
        lbl_ID = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 218, 157));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProductos.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "MODELO", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(0).setPreferredWidth(20);
            tablaProductos.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaProductos.getColumnModel().getColumn(2).setPreferredWidth(22);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 820, 320));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTION DE PRODUCTOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("MARCA :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(255, 102, 0));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("BUSCAR");
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 110, 30));

        btnLimpiar.setBackground(new java.awt.Color(255, 153, 0));
        btnLimpiar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 204, 102), null, null));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 120, 30));

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("TIPO :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        comboMarca.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        add(comboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 200, -1));

        comboTipo.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        add(comboTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 200, -1));

        lbl_ID.setForeground(new java.awt.Color(255, 218, 157));
        add(lbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        cargarTabla();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked

        int fila = this.tablaProductos.rowAtPoint(evt.getPoint());
        this.lbl_ID.setText(this.tablaProductos.getValueAt(fila, 0).toString());
        this.comboMarca.getModel().setSelectedItem(new Marca(Integer.parseInt(this.tablaProductos.getValueAt(fila, 2).toString()),this.tablaProductos.getValueAt(fila, 3).toString()));
        this.comboTipo.getModel().setSelectedItem(new Genericos(Integer.parseInt(this.tablaProductos.getValueAt(fila, 6).toString()),this.tablaProductos.getValueAt(fila, 7).toString()));
    }//GEN-LAST:event_tablaProductosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
